### ISSUE TITLE
what happened to 'config.iterStyle = IterationStyle.everything;' etc?

### ISSUE THREAD

**Issue by timotheecour** [Hackerpilot/libdparse#108]
Previous code I have used:
config.iterStyle = IterationStyle.everything;
this doesn't compile anymore.
```git log -S IterationStyle```
doesn't return anything, so I can't trace it back to where it disappeared.

http://hackerpilot.github.io/experimental/std_lexer/phobos/std_d_lexer.html
still shows some remnants of this pattern however (eg: config.iterStyle = IterationStyle.everything)

what should I replace it by?

**Comment by Hackerpilot** [comment]
The lexer call used by D-Scanner's code highlighter is here: https://github.com/Hackerpilot/Dscanner/blob/master/src/main.d#L181. You want a combination of `StringBehavior.source`, and `WhitespaceBehavior.include`.

**Comment by timotheecour** [comment]
thanks!
