### ISSUE TITLE
[help wanted] symbol list from ast

### ISSUE THREAD

**Issue by BBasile** [Hackerpilot/libdparse#22]
I'd like to write a symbol list module for Coedit based on libdparse. I'm in front of a problem, how can I templatize this pattern ?

```D
auto config = LexerConfig(filename, StringBehavior.source);
StringCache cache = StringCache(StringCache.defaultBucketCount);
const(Token)[] tokens = getTokensForParser(rawSrc, config, &cache);
auto ast = parseModule(tokens, filename, null, null);
Declaration[] decls = ast.declarations;
if(!decls.length) return;  

foreach(q;queries)
{
    // class declarations  
    if (q == "cl")
    {
        string classNames = q ~ "=\"";
        foreach(i; 0 .. decls.length)
            if (decls[i].classDeclaration !is null)
                classNames ~= decls[i].classDeclaration.name.text ~';';
        classNames ~= "\"";
        writeln(classNames);
        continue;                  
    }     
    // structure declarations
    if (q == "st")
    {
        string structNames = q ~ "=\"";
        foreach(i; 0 .. decls.length)
            if (decls[i].structDeclaration !is null)
            structNames ~= decls[i].structDeclaration.name.text ~';';
        structNames ~= "\"";
        writeln(structNames);   
        continue;               
    }     
   // etc, following the pattern for interfaces, functions, templates, imports,...
}
```
each member list of a cat is get from the same fashion, but since a category is actually a member of a node, I cant see how to templatize the thing:

```D
void listOf(C)(string category)
{
    string list = category ~ "=\"";
    foreach(i; 0 .. decls.length)
        if (cast(C)decls[i] !is null)
            list ~= (cast(C)decls[i]).name.text ~';';
        list ~= "\""; 
    writeln(list);      
}
```
does not work. I could list everything but the background problem is that the members to enumerate rely on a list of query, sometime just the module name, sometime just the classes. etc. Rhx, sorry to post this Q here, maybe not the right place.

**Comment by BBasile** [comment]
I have two questions about the usage, i will use libdparse to replace dmd json output in Coedit but here:

https://github.com/BBasile/Coedit/blob/master/cesyms/cesyms.d#L217

how can i handle the old alias syntax ?
why is "initializers" an array ?

**Comment by Hackerpilot** [comment]
Running `dscanner --ast` on your D file will show you what the AST looks like.

**Comment by BBasile** [comment]
Thx this _perfectly_ answers the question. cough.

**Comment by Hackerpilot** [comment]
I'm going to assume that was sarcasm. I am serious about looking at the AST dump being the best way to figure out how to build your listener class.

**Comment by BBasile** [comment]
Sorry for the misunderstanding, i thought you had suggested to use DScanner instead of making my own program. Time to take a break...
