### ISSUE TITLE
Certain version statements without braces or inside function bodies cannot be found

### ISSUE THREAD

**Issue by joakim-noah** [Hackerpilot/libdparse#28]
I've modified Dscanner to help me find all version blocks in druntime that have a default else block which doesn't contain a static assert, and it was working well for that purpose.  However, I noticed when going through some modules that it was missing some version blocks, those inside functions.  When experimenting with the following test input, I noticed that it sometimes also won't find version blocks without braces.  

Here's some D input that shows the problems:

```D
version (linux)
{   printf("got here");}
else version (Android)
{   printf("got in here");}

void foo() {
    version (linux)
    {     printf("got here");}
    else version (Android)
    {     printf("got in here");}

    version (linux) int x = 3;
    else version (Android) int y = 5;
}

version (linux) printf("got here");
else version (Android) printf("got in here");
```

The first two version blocks are exactly the same, the fourth is the same as the first two but without braces.

I modified the symbol finder in Dscanner to notify on every version statement it finds:

```diff
--- a/src/symbol_finder.d
+++ b/src/symbol_finder.d
@@ -99,7 +99,14 @@ class FinderVisitor : ASTVisitor
                }
        }

-       override void visit(const FunctionBody) {}
+       //override void visit(const FunctionBody fb) {output.writefln("found a function body");fb.accept(this);}
+
+       override void visit(const ConditionalDeclaration cd)
+        {
+            if(cd.compileCondition.versionCondition)
+            output.writefln("version checked is %s at line %d", cd.compileCondition.versionCondition.token.text, cd.compileCondition.versionCondition.token.line);
+           cd.accept(this);
+        }

        mixin template generateVisit(T)
        {

```

Running it on the input produces the following output:

```
version checked is linux at line 1
version checked is Android at line 3
version checked is linux at line 12
version checked is Android at line 13
```

The modified Dscanner only finds the first and third version blocks.  It seems to miss the second version block because it's inside a function body and the fourth one because it doesn't have braces.  However, those reasons don't seem to apply to the third version block, which is inside the function body and doesn't have braces.

I tried commenting out all the other node overrides in the Dscanner visitor, to see if they were interfering, but that didn't make a difference.

**Comment by joakim-noah** [comment]
Updated both libdparse and Dscanner to their latest commits and I don't see any difference when using the above test input and this similar Dscanner patch, ie it's still making the same mistakes on the version blocks at module scope:

```diff
diff --git a/src/symbol_finder.d b/src/symbol_finder.d
index 32ef86b..0f61b18 100644
--- a/src/symbol_finder.d
+++ b/src/symbol_finder.d
@@ -99,7 +99,23 @@ class FinderVisitor : ASTVisitor
                }
        }

-       override void visit(const FunctionBody) {}
+       override void visit(const FunctionBody fb) {fb.accept(this);}
+
+       override void visit(const ConditionalDeclaration cd)
+        {
+            if (cd.compileCondition.versionCondition)
+                output.writefln("version condition checked is %s at line %d",
+                              fileName, cd.compileCondition.versionCondition.token.line);
+           cd.accept(this);
+        }
+
+       override void visit(const ConditionalStatement cs)
+        {
+            if (cs.compileCondition.versionCondition)
+                output.writefln("version statement checked is %s at line %d",
+                              fileName, cs.compileCondition.versionCondition.token.line);
+           cs.accept(this);
+        }

        mixin template generateVisit(T)
        {
```

**Comment by Hackerpilot** [comment]
I think I found out what's going on: The symbol finder intentionally doesn't print parse errors. Try running "dscanner -s" (or --syntaxCheck) on your code and it should print the errors.

**Comment by joakim-noah** [comment]
Yep, the symbol finder won't handle such code errors, but the syntax check reports them.

**Comment by Hackerpilot** [comment]
If you don't have any more questions you can close this issue.
