### ISSUE TITLE
Parse errors in ae library

### ISSUE THREAD

**Issue by CyberShadow** [Hackerpilot/libdparse#29]
I'm counting 75 `[error]` lines when running DScanner against my ae library:

https://github.com/CyberShadow/ae

**Comment by Hackerpilot** [comment]
I fixed all but one error:
```d
alias this save;
```
I'm not even sure that this is valid.

**Comment by CyberShadow** [comment]
Thanks! And yeah, that looks like an "accepts-invalid" which I never tested. The intent was `@property ref typeof(this) save() { return this; }`

Here's a new one I introduced only yesterday:

https://github.com/CyberShadow/ae/blob/d734ddcd0133a0c4660d3f6b49d78d05f4e5a5d6/net/ssl/openssl.d#L125

```
C:\Projects\ae\net\ssl\openssl.d(125:15)[error]: Basic type, type constructor, symbol, or typeof expected
```

**Comment by Hackerpilot** [comment]
https://issues.dlang.org/show_bug.cgi?id=13943
