### ISSUE TITLE
Invalid error message when an opIndex uses several opSlices

### ISSUE THREAD

**Issue by Blumerline** [Hackerpilot/libdparse#67]
for a custom type that takes two ints in opSlice and also overload opIndex

```D
CustomType t = CustomType[0..9, 1..6];
```

libdparse produces the following error about the comma between the two opSlices:
> Expected ] instead of ,

while this is not error

**Comment by Hackerpilot** [comment]
You've found another bug in the language specification. Search here (http://dlang.org/grammar.html) for the ".." operator, you won't be able to find a way to make `[0..9, 1..6]` using the official grammar.

**Comment by Hackerpilot** [comment]
https://issues.dlang.org/show_bug.cgi?id=15250

**Comment by Blumerline** [comment]
In case you'll fix it also note that, according to http://dlang.org/operatoroverloading.html#slice, this forms are also valid for `opIndexAssign` and `opIndexOpAssign`. 

It's even allowed to mix the indexers kinds and forms if the overloads are present (for example this extrem case could be totally valid `a = b[0, 2..5, 7..$, 'A', "CF", MyStruct(0)..MyStruct(8)]` !).

**Comment by Hackerpilot** [comment]
I think I'm going to remove the `sliceExpression` rule and modify `indexExpression` like this:
```
 indexExpression:
       unaryExpression '[' ']'
     | unaryExpression '[' index (',' index)* ']'
     ;
 index:
     assignExpression ('..' assignExpression)?
     ;
```

**Comment by Hackerpilot** [comment]
https://github.com/D-Programming-Language/dlang.org/pull/1143

**Comment by Blumerline** [comment]
Thx.
