### ISSUE TITLE
Release - Git tag needed for dmd 2.069

### ISSUE THREAD

**Issue by ghost** [Hackerpilot/libdparse#68]
If I put libdparse as a DUB dependency, DUB will fetch 0.2.1 which is quite obsolete now.

**Comment by mathias-lang-sociomantic** [comment]
@Hackerpilot : A release would be greatly appreciated.

**Comment by Hackerpilot** [comment]
I'm planning on tagging one soon.

**Comment by mathias-lang-sociomantic** [comment]
Ping

**Comment by Hackerpilot** [comment]
I want to fix https://github.com/Hackerpilot/libdparse/issues/69 before the next release.

**Comment by mathias-lang-sociomantic** [comment]
That rocks ! Thanks a lot :)
