### ISSUE TITLE
The trailing comments sometimes get lost.

### ISSUE THREAD

**Issue by adamdruppe** [Hackerpilot/libdparse#74]
The ddoc page here  http://dlang.org/spec/ddoc.html says "Multiple documentation comments applying to the same declaration are concatenated" and this example demos it with block and trailing:

```
/** documentation for g */
int g; /// more documentation for g
```

libdparse does not seem to recognize this:

```
        node.comment = start.comment;
        if (node.comment is null)
            node.comment = start.trailingComment;
```

That's from https://github.com/Hackerpilot/libdparse/blob/master/src/dparse/parser.d#L3911 but the same pattern appears throughout the parser.

There also seem to be a few cases where the trailing comment just gets lost too, like in parsing an `AliasDeclaration`: https://github.com/Hackerpilot/libdparse/blob/master/src/dparse/parser.d#L84

And I don't see it attached on the initializer list either, though I might be missing something there, I don't know your code very well yet.

With this test case:

```
/// test
alias cool = string; /// which comment is there?
```

I ran it through the visitor and checked AliasDeclaration.comment and it only gave me "/// test". If I take the top comment off, the comment is null.

My guess is what you'll want to do is remove those if(null) conditions and use ~= instead, but the whole allocation business probably makes that a bit more than it seems...

**Comment by Hackerpilot** [comment]
I have a fix coded up for your alias example.

The docs for your variable declaration example are not lost, but they're not where you expect them either. `dscanner --ast test.d | xmllint --format` gives output like this:
```xml
<?xml version="1.0"?>
<module>
  <declaration>
    <variableDeclaration>
      <ddoc>/** documentation for g */</ddoc>
      <type pretty="int">
        <type2>int</type2>
      </type>
      <declarator line="2">
        <name>g</name>
        <ddoc>/// more documentation for g</ddoc>
      </declarator>
    </variableDeclaration>
  </declaration>
</module>
```

The first comment is attached to the variable declaration, but the second is attached to the declarator. I think that I wrote it this way so that you can have different trailing doc comments for each declarator, though I can tell that I didn't test this well enough.

Check this out:
```d
/// doc1
int a, /// doc2
	b, /// doc3
	c; /// doc4
```
Build with `dmd -c -D test.d` and look at the html file. You'll get something like this:
```
int a;
    doc1
    doc2

int b;
    doc1
    doc3

int c;
    doc1
    doc4
```

The ddoc spec doesn't really say that this should happen, but it doesn't say that it shouldn't either.

**Comment by Hackerpilot** [comment]
I started a thread to get some input on this: http://forum.dlang.org/post/kdwwndlsbecdxuhxisqb@forum.dlang.org

**Comment by adamdruppe** [comment]
On Wed, Jan 06, 2016 at 06:11:10PM -0800, Brian Schott wrote:
> The docs for your variable declaration example are not lost, but they're not where you expect them either. `dscanner --ast test.d | xmllint --format` gives output like this:

Aye, I realized this earlier today too, it makes sense when I think about it.

**Comment by Hackerpilot** [comment]
With my most recent change the AST will look like this:
```xml
<?xml version="1.0"?>
<module>
  <declaration>
    <variableDeclaration>
      <ddoc>/// doc1</ddoc>
      <type pretty="int">
        <type2>int</type2>
      </type>
      <declarator line="9">
        <name>a</name>
        <ddoc>/// doc1
/// doc2</ddoc>
      </declarator>
      <declarator line="10">
        <name>b</name>
        <ddoc>/// doc1
/// doc3</ddoc>
      </declarator>
      <declarator line="11">
        <name>c</name>
        <ddoc>/// doc1
/// doc4</ddoc>
      </declarator>
    </variableDeclaration>
  </declaration>
</module>
```
