### ISSUE TITLE
crash in parseModule() - head on master

### ISSUE THREAD

**Issue by BBasile** [Hackerpilot/libdparse#87]
```D
import std.file;
import dparse.lexer, dparse.ast, dparse.parser;

void main(string[] args)
{
    auto source = cast(ubyte[]) read(__FILE__, size_t.max);
    auto config = LexerConfig(__FILE__, StringBehavior.source, WhitespaceBehavior.skip);
    auto scache = StringCache(StringCache.defaultBucketCount);
    auto ast = parseModule(getTokensForParser(source, config, &scache), __FILE__, null);
}
```

crashes and returns the signal 11.

I'm on 6a42726a7b8286df19db561a2f35f75d8c4a9e77
The last sane version for me is 2f91d07f698545ebc94ede00d5085aa59dbe38b3.
Seems to be related to the rollback allocator added since.

**Comment by Hackerpilot** [comment]
Don't pass `null` as the allocator argument.

**Comment by BBasile** [comment]
I think I've missed the point with the updates made since 3 weeks. What should I use for simple "one shot" programs ? Mallocator is Ok ?

**Comment by BBasile** [comment]
Ok always a Rollback allocator. Thx for the quick help.
