### ISSUE TITLE
core.exception.RangeError@../../.dub/packages/libdparse-0.5.0/src/dparse/lexer.d(979): Range violation

### ISSUE THREAD

**Issue by miotatsu** [Hackerpilot/libdparse#88]
I get an exception from dparse when I try to generate documentation for a project with ddox:
https://gist.github.com/miotatsu/c4fc6b41aa077595be56

**Comment by Hackerpilot** [comment]
I get the feeling that I've seen this bug before. Looks like you're using version 0.5.0 when 0.6.0 is the latest release.

**Comment by Hackerpilot** [comment]
https://github.com/Hackerpilot/libdparse/commit/adb134c054ffcb05c74d7033e59617dedba1493b

This is part of 0.6.0. See if you can update the dependency.
